package ru.liga.common.enums;

public enum ActionType {
    ORDER_CUSTOMER_CREATED,
    ORDER_CUSTOMER_PAID,
    ORDER_CUSTOMER_CANCELLED,
    ORDER_CUSTOMER_PAID_AND_CANCELLED,
    ORDER_DELIVERY_PENDING,
    ORDER_KITCHEN_ACCEPTED,
    ORDER_KITCHEN_PREPARING,
    ORDER_KITCHEN_DENIED,
    ORDER_KITCHEN_REFUNDED,
    ORDER_DELIVERY_PICKING,
    ORDER_DELIVERY_DELIVERING,
    ORDER_DELIVERY_COMPLETE,
    ORDER_DELIVERY_DENIED,
    ORDER_DELIVERY_REFUNDED,
    ADD_COURIER,
    FIND_COURIER,
    NEW_ORDER_FOR_RESTAURANT
}

